/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodosRouteImport } from './routes/_app/todos'
import { Route as AppSaasRouteImport } from './routes/_app/saas'
import { Route as AppPaginasRouteImport } from './routes/_app/paginas'
import { Route as AppNovoRouteImport } from './routes/_app/novo'
import { Route as AppN8nRouteImport } from './routes/_app/n8n'
import { Route as AppIaRouteImport } from './routes/_app/ia'
import { Route as AppPIdRouteImport } from './routes/_app/p.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any)
const AppSaasRoute = AppSaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => AppRoute,
} as any)
const AppPaginasRoute = AppPaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => AppRoute,
} as any)
const AppNovoRoute = AppNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppN8nRoute = AppN8nRouteImport.update({
  id: '/n8n',
  path: '/n8n',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppPIdRoute = AppPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ia': typeof AppIaRoute
  '/n8n': typeof AppN8nRoute
  '/novo': typeof AppNovoRoute
  '/paginas': typeof AppPaginasRoute
  '/saas': typeof AppSaasRoute
  '/todos': typeof AppTodosRoute
  '/p/$id': typeof AppPIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ia': typeof AppIaRoute
  '/n8n': typeof AppN8nRoute
  '/novo': typeof AppNovoRoute
  '/paginas': typeof AppPaginasRoute
  '/saas': typeof AppSaasRoute
  '/todos': typeof AppTodosRoute
  '/p/$id': typeof AppPIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/n8n': typeof AppN8nRoute
  '/_app/novo': typeof AppNovoRoute
  '/_app/paginas': typeof AppPaginasRoute
  '/_app/saas': typeof AppSaasRoute
  '/_app/todos': typeof AppTodosRoute
  '/_app/p/$id': typeof AppPIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ia'
    | '/n8n'
    | '/novo'
    | '/paginas'
    | '/saas'
    | '/todos'
    | '/p/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ia'
    | '/n8n'
    | '/novo'
    | '/paginas'
    | '/saas'
    | '/todos'
    | '/p/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ia'
    | '/_app/n8n'
    | '/_app/novo'
    | '/_app/paginas'
    | '/_app/saas'
    | '/_app/todos'
    | '/_app/p/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/todos': {
      id: '/_app/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saas': {
      id: '/_app/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof AppSaasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paginas': {
      id: '/_app/paginas'
      path: '/paginas'
      fullPath: '/paginas'
      preLoaderRoute: typeof AppPaginasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/novo': {
      id: '/_app/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AppNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/n8n': {
      id: '/_app/n8n'
      path: '/n8n'
      fullPath: '/n8n'
      preLoaderRoute: typeof AppN8nRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$id': {
      id: '/_app/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AppPIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIaRoute: typeof AppIaRoute
  AppN8nRoute: typeof AppN8nRoute
  AppNovoRoute: typeof AppNovoRoute
  AppPaginasRoute: typeof AppPaginasRoute
  AppSaasRoute: typeof AppSaasRoute
  AppTodosRoute: typeof AppTodosRoute
  AppPIdRoute: typeof AppPIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIaRoute: AppIaRoute,
  AppN8nRoute: AppN8nRoute,
  AppNovoRoute: AppNovoRoute,
  AppPaginasRoute: AppPaginasRoute,
  AppSaasRoute: AppSaasRoute,
  AppTodosRoute: AppTodosRoute,
  AppPIdRoute: AppPIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
